set_property SRC_FILE_INFO {cfile:{D:/Work and shit/Github/Files/BigDcore/Vivado projects/RV32ICore/RV32ICore V2/RV32ICore V2.srcs/constrs_1/new/MainConstrainsts.xdc} rfile:{../../../../../RV32ICore/RV32ICore V2/RV32ICore V2.srcs/constrs_1/new/MainConstrainsts.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports clock]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports reset_IN]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {LEDTest[1]}]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {LEDTest[0]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][24]_0}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][13]_0}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][5]_0}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][11]_0}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][14]_0}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][16]_0}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][31]_0}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][17]_0}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][18]_0}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][27]_0}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][4]_0}]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][3]_0}]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][8]_0}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][9]_0}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][10]_0}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][15]_0}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][21]_0}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][28]_0}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][30]_0}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][1]_0}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][2]_0}]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][7]_0}]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][25]_0}]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][6]_0}]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][12]_0}]
set_property src_info {type:XDC file:1 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][19]_0}]
set_property src_info {type:XDC file:1 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][20]_0}]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][22]_0}]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][23]_0}]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][26]_0}]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[135][29]_0}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][0]_0}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][4]_0}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][8]_0}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][12]_0}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][13]_0}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][16]_0}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][28]_0}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][30]_0}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][27]_0}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][2]_0}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][5]_0}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][7]_0}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][18]_0}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][21]_0}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][3]_0}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][6]_0}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][11]_0}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][15]_0}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][24]_0}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][25]_0}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][26]_0}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][31]_0}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][9]_0}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][23]_0}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][1]_0}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][10]_0}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][14]_0}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][17]_0}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][19]_0}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][20]_0}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][22]_0}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {Data_RAM/Mem_reg[22][29]_0}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[2][16]_0}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[2][17]_0}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[2][18]_0}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {Data_RAM/Mem_reg[2][19]_0}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[12]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[15]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[17]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[19]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[23]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[24]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[27]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[29]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[0]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[5]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[7]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[9]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[18]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[21]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[26]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[3]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[1]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[2]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[6]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[10]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[11]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[13]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[14]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[28]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[16]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[25]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[30]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[4]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[8]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[20]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[22]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {CPU/Datapath/Register_File/M_reg[1][31]_0[31]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clock_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {CPU/Datapath/Register_File/M_reg[1][31]_0[0]} {CPU/Datapath/Register_File/M_reg[1][31]_0[1]} {CPU/Datapath/Register_File/M_reg[1][31]_0[2]} {CPU/Datapath/Register_File/M_reg[1][31]_0[3]} {CPU/Datapath/Register_File/M_reg[1][31]_0[4]} {CPU/Datapath/Register_File/M_reg[1][31]_0[5]} {CPU/Datapath/Register_File/M_reg[1][31]_0[6]} {CPU/Datapath/Register_File/M_reg[1][31]_0[7]} {CPU/Datapath/Register_File/M_reg[1][31]_0[8]} {CPU/Datapath/Register_File/M_reg[1][31]_0[9]} {CPU/Datapath/Register_File/M_reg[1][31]_0[10]} {CPU/Datapath/Register_File/M_reg[1][31]_0[11]} {CPU/Datapath/Register_File/M_reg[1][31]_0[12]} {CPU/Datapath/Register_File/M_reg[1][31]_0[13]} {CPU/Datapath/Register_File/M_reg[1][31]_0[14]} {CPU/Datapath/Register_File/M_reg[1][31]_0[15]} {CPU/Datapath/Register_File/M_reg[1][31]_0[16]} {CPU/Datapath/Register_File/M_reg[1][31]_0[17]} {CPU/Datapath/Register_File/M_reg[1][31]_0[18]} {CPU/Datapath/Register_File/M_reg[1][31]_0[19]} {CPU/Datapath/Register_File/M_reg[1][31]_0[20]} {CPU/Datapath/Register_File/M_reg[1][31]_0[21]} {CPU/Datapath/Register_File/M_reg[1][31]_0[22]} {CPU/Datapath/Register_File/M_reg[1][31]_0[23]} {CPU/Datapath/Register_File/M_reg[1][31]_0[24]} {CPU/Datapath/Register_File/M_reg[1][31]_0[25]} {CPU/Datapath/Register_File/M_reg[1][31]_0[26]} {CPU/Datapath/Register_File/M_reg[1][31]_0[27]} {CPU/Datapath/Register_File/M_reg[1][31]_0[28]} {CPU/Datapath/Register_File/M_reg[1][31]_0[29]} {CPU/Datapath/Register_File/M_reg[1][31]_0[30]} {CPU/Datapath/Register_File/M_reg[1][31]_0[31]}]]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clock_IBUF_BUFG]
