set_property SRC_FILE_INFO {cfile:{D:/Work and shit/Github/Files/BigDcore/Vivado projects/RV32ICore/RV32ICore V2/RV32ICore V2.srcs/constrs_1/new/MainConstrainsts.xdc} rfile:{../../../RV32ICore V2.srcs/constrs_1/new/MainConstrainsts.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N18 [get_ports clock]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P16 [get_ports reset_IN]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P15 [get_ports {LEDTest[0]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U12 [get_ports {LEDTest[1]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets CPU/Datapath/PC_PLR/clock_IBUF_BUFG]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list clock_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 31 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {CPU/Datapath/instruction_PLR/D[0]} {CPU/Datapath/instruction_PLR/D[1]} {CPU/Datapath/instruction_PLR/D[2]} {CPU/Datapath/instruction_PLR/D[3]} {CPU/Datapath/instruction_PLR/D[4]} {CPU/Datapath/instruction_PLR/D[5]} {CPU/Datapath/instruction_PLR/D[6]} {CPU/Datapath/instruction_PLR/D[7]} {CPU/Datapath/instruction_PLR/D[8]} {CPU/Datapath/instruction_PLR/D[9]} {CPU/Datapath/instruction_PLR/D[10]} {CPU/Datapath/instruction_PLR/D[11]} {CPU/Datapath/instruction_PLR/D[12]} {CPU/Datapath/instruction_PLR/D[13]} {CPU/Datapath/instruction_PLR/D[14]} {CPU/Datapath/instruction_PLR/D[15]} {CPU/Datapath/instruction_PLR/D[16]} {CPU/Datapath/instruction_PLR/D[17]} {CPU/Datapath/instruction_PLR/D[18]} {CPU/Datapath/instruction_PLR/D[19]} {CPU/Datapath/instruction_PLR/D[20]} {CPU/Datapath/instruction_PLR/D[21]} {CPU/Datapath/instruction_PLR/D[22]} {CPU/Datapath/instruction_PLR/D[23]} {CPU/Datapath/instruction_PLR/D[24]} {CPU/Datapath/instruction_PLR/D[25]} {CPU/Datapath/instruction_PLR/D[26]} {CPU/Datapath/instruction_PLR/D[27]} {CPU/Datapath/instruction_PLR/D[28]} {CPU/Datapath/instruction_PLR/D[29]} {CPU/Datapath/instruction_PLR/D[30]}]]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {CPU/Datapath/Pc_Register/Q[0]} {CPU/Datapath/Pc_Register/Q[1]} {CPU/Datapath/Pc_Register/Q[2]} {CPU/Datapath/Pc_Register/Q[3]} {CPU/Datapath/Pc_Register/Q[4]} {CPU/Datapath/Pc_Register/Q[5]} {CPU/Datapath/Pc_Register/Q[6]} {CPU/Datapath/Pc_Register/Q[7]} {CPU/Datapath/Pc_Register/Q[8]} {CPU/Datapath/Pc_Register/Q[9]} {CPU/Datapath/Pc_Register/Q[10]} {CPU/Datapath/Pc_Register/Q[11]} {CPU/Datapath/Pc_Register/Q[12]} {CPU/Datapath/Pc_Register/Q[13]} {CPU/Datapath/Pc_Register/Q[14]} {CPU/Datapath/Pc_Register/Q[15]} {CPU/Datapath/Pc_Register/Q[16]} {CPU/Datapath/Pc_Register/Q[17]} {CPU/Datapath/Pc_Register/Q[18]} {CPU/Datapath/Pc_Register/Q[19]} {CPU/Datapath/Pc_Register/Q[20]} {CPU/Datapath/Pc_Register/Q[21]} {CPU/Datapath/Pc_Register/Q[22]} {CPU/Datapath/Pc_Register/Q[23]} {CPU/Datapath/Pc_Register/Q[24]} {CPU/Datapath/Pc_Register/Q[25]} {CPU/Datapath/Pc_Register/Q[26]} {CPU/Datapath/Pc_Register/Q[27]} {CPU/Datapath/Pc_Register/Q[28]} {CPU/Datapath/Pc_Register/Q[29]} {CPU/Datapath/Pc_Register/Q[30]} {CPU/Datapath/Pc_Register/Q[31]}]]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list CPU/Datapath/PC_PLR/clock_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets clock_IBUF_BUFG]
